[package]
name = "house-automationd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "house-automationd"
path = "src/main.rs"

[dependencies]
house-automation-core = { path = "../house-automation-core" }
serde_json = "1"
